### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by InspiritW** [Dheerajmadhukar/4-ZERO-3#1]
hi just wanted to ask how do I like export? the request this script made so I can use it in a browser?

**Comment by Dheerajmadhukar** [comment]
You can grep the payload from script. 

# cat 403-bypass.sh | grep -i "X-Rewrite-URL"

That will give you the cURL output and you can use the same as payload.

**Comment by tahamarzak20** [comment]
hi Sir i want to ask if i can put a list of hosts to test for

**Comment by Dheerajmadhukar** [comment]
cat hosts.txt | xargs -P50 -I@ bash -c "bash 403-bypass.sh '@'"
