### ISSUE TITLE
Error in Termux 

### ISSUE THREAD

**Issue by 0xnaeem** [Dheerajmadhukar/4-ZERO-3#8]
![Screenshot_2022-03-10-18-22-00-52_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/75798132/157660813-44dbda56-2f1d-4561-8e22-77cb12e8628f.jpg)

**Comment by Dheerajmadhukar** [comment]
Unfortunately , Script doesn't support `termux` right now! You have to use it on Linux OS.
